Allowance contract
GerschheimerDidier/DevFest2022 pull request #1
Opened 2022-10-11 14:20 UTC by AGeorgeon

This contracts can be used on Shared wallet and communal fund

2022-10-12 08:15 UTC, AGeorgeon commented on truffle/contracts/Allowance.sol
> +        require(isOwner() || accountBeneficiary[_who] > 0, "You are not the owner or this address is already on this wallet, please update it");
Mettre un &&

2022-10-12 08:20 UTC, AGeorgeon commented on truffle/contracts/Allowance.sol
> +        emit AllowanceChanged(_who, msg.sender, accountBeneficiary[_who], _newAmount);
event à la fin de la fonction

2022-10-12 08:20 UTC, AGeorgeon commented on truffle/contracts/Allowance.sol
> +        revert();
Verifier les guide line et sinon mettre -1

2022-10-19 09:01 UTC, GerschheimerDidier requested changes

2022-10-19 09:01 UTC, GerschheimerDidier commented on truffle/test/allowance.test.js
> +      const allowanceMapping = await this.allowanceInstance.accountBeneficiary(accounts[5]);
```suggestion
      const allowanceMapping = await this.allowanceInstance.accountBeneficiary(beneficiary);
```

2022-10-19 09:01 UTC, GerschheimerDidier commented on truffle/test/allowance.test.js
> +        accounts[5],
```suggestion
        beneficiary,
```

2022-10-19 09:01 UTC, GerschheimerDidier commented on truffle/test/allowance.test.js
> +      const allowanceMapping = await this.allowanceInstance.accountBeneficiary(accounts[5]);
```suggestion
      const allowanceMapping = await this.allowanceInstance.accountBeneficiary(beneficiary);
```

2022-10-26 06:51 UTC, merged